package com.ak.ems.dto;

import com.ak.ems.entity.AttendanceStatus;
import com.ak.ems.entity.WorkMode;
import io.swagger.v3.oas.annotations.media.Schema;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AttendanceDto {

    @Schema(description = "Autogenerated by database", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    private Long employeeId;

    private String employeeName;

    private LocalDate date;

    private LocalTime checkIn;

    private LocalTime checkOut;

    private AttendanceStatus status;

    private WorkMode workMode;
    private Double latitude;
    private Double longitude;

    private String remarks;
    private Boolean isManager;
    private Boolean isTeamLeader;
    private Double workingHours;
}
