package com.ak.ems.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

import java.time.LocalDate;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class EmployeeDto {

    @io.swagger.v3.oas.annotations.media.Schema(description = "Autogenerated by database", accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_ONLY)
    private Long id;
    
    @NotBlank(message = "First name is mandatory")
    private String firstName;
    
    private String lastName;
    
    @NotBlank(message = "Email is mandatory")
    @Email(message = "Email should be valid")
    private String email;

    private String phone;
    private String designation;
    private LocalDate joiningDate;
    private String address;

    private java.util.Set<String> skills;
    private Long departmentId;
    private String departmentName;
    private Long teamId;
    private String teamName;
    private Long userId;

    private String username;
    private String password;
    private String role;
}
