package com.ak.ems.dto;

import com.ak.ems.entity.LeaveStatus;
import com.ak.ems.entity.LeaveType;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class LeaveRequestDto {

    @Schema(description = "Autogenerated by database", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @NotNull(message = "Employee ID is required")
    private Long employeeId;

    @Schema(description = "Read-only, set by backend", accessMode = Schema.AccessMode.READ_ONLY)
    private String employeeName;

    @NotNull(message = "Leave Type is required")
    private LeaveType leaveType;

    @NotNull(message = "Start Date is required")
    @FutureOrPresent(message = "Start date must be in the present or future")
    private LocalDate startDate;

    @NotNull(message = "End Date is required")
    @FutureOrPresent(message = "End date must be in the present or future")
    private LocalDate endDate;

    @Schema(description = "Read-only status", accessMode = Schema.AccessMode.READ_ONLY)
    private LeaveStatus status;

    private String reason;

    private String adminRemarks;
}
