package com.ak.ems.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TeamDto {

    @io.swagger.v3.oas.annotations.media.Schema(description = "Autogenerated by database", accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_ONLY)
    private Long id;

    @NotBlank(message = "Team name is required")
    private String name;

    private String description;

    // Adding departmentId to easily assign teams to departments via the API
    private Long departmentId;
    private String departmentName;

    private Long teamLeaderId;
    private String teamLeaderName;
}
