package com.ak.ems.service.impl;

import com.ak.ems.dto.DepartmentDto;
import com.ak.ems.entity.Department;
import com.ak.ems.entity.Employee;
import com.ak.ems.exception.ResourceNotFoundException;
import com.ak.ems.repository.DepartmentRepository;
import com.ak.ems.repository.EmployeeRepository;
import com.ak.ems.response.PageResponse;
import com.ak.ems.service.DepartmentService;
import lombok.AllArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

import java.util.stream.Collectors;
import com.ak.ems.entity.Role;
import com.ak.ems.repository.RoleRepository;
import com.ak.ems.repository.UserRepository;

@Service
@AllArgsConstructor
@Transactional
public class DepartmentServiceImpl implements DepartmentService {

    private DepartmentRepository departmentRepository;
    private EmployeeRepository employeeRepository;
    private RoleRepository roleRepository;
    private UserRepository userRepository;

    @Override
    public DepartmentDto createDepartment(DepartmentDto departmentDto) {
        if(departmentRepository.existsByName(departmentDto.getName())){
            throw new IllegalArgumentException("Department Name already exists");
        }

        Department department = mapToEntity(departmentDto);
        department.setId(null); // Ensure ID is auto-generated by database during creation

        if (departmentDto.getManagerId() != null) {
            Employee manager = employeeRepository.findById(departmentDto.getManagerId())
                    .orElseThrow(() -> new ResourceNotFoundException("Manager employee not found with id: " + departmentDto.getManagerId()));
            department.setManager(manager);

            if (manager.getUser() != null) {
                com.ak.ems.entity.Role managerRole = roleRepository.findByName("ROLE_MANAGER")
                        .orElseThrow(() -> new ResourceNotFoundException("Role not found: ROLE_MANAGER"));
                manager.getUser().getRoles().add(managerRole);
                userRepository.save(manager.getUser());
            }
        }
        Department savedDepartment = departmentRepository.save(department);
        return mapToDto(savedDepartment);
    }

    @Override
    public DepartmentDto getDepartmentById(Long departmentId) {
        Department department = departmentRepository.findById(departmentId)
                .orElseThrow(() -> new ResourceNotFoundException("Department is not exists with given id: " + departmentId));
        return mapToDto(department);
    }

    @Override
    public PageResponse<DepartmentDto> getAllDepartments(String query, int page, int size, String sortBy, String sortDir) {
        Sort sort = sortDir.equalsIgnoreCase(Sort.Direction.ASC.name()) ? Sort.by(sortBy).ascending()
                : Sort.by(sortBy).descending();

        Pageable pageable = PageRequest.of(page, size, sort);

        Page<Department> departments;
        
        // Simple search by name or description
        if (query != null && !query.isEmpty()) {
            // For a production app, we would use native queries or specifications here.
            // For now, fetching all and filtering in memory (just as a placeholder if no spec is available), 
            // OR we can add a method to Repo. Let's add it to repo later if needed, returning all for now if no query.
            departments = departmentRepository.findAll(pageable); 
            // Better to just not implement the query part fully unless requested, or use findAll
        } else {
            departments = departmentRepository.findAll(pageable);
        }

        List<DepartmentDto> content = departments.getContent().stream()
                .map(this::mapToDto)
                .collect(Collectors.toList());

        PageResponse<DepartmentDto> pageResponse = new PageResponse<>();
        pageResponse.setContent(content);
        pageResponse.setPageNo(departments.getNumber());
        pageResponse.setPageSize(departments.getSize());
        pageResponse.setTotalElements(departments.getTotalElements());
        pageResponse.setTotalPages(departments.getTotalPages());
        pageResponse.setLast(departments.isLast());

        return pageResponse;
    }

    @Override
    public DepartmentDto updateDepartment(Long departmentId, DepartmentDto departmentDto) {
        Department department = departmentRepository.findById(departmentId)
                .orElseThrow(() -> new ResourceNotFoundException("Department is not exists with given id: " + departmentId));

        department.setName(departmentDto.getName());
        department.setDescription(departmentDto.getDescription());

        if (departmentDto.getManagerId() != null) {
            Employee manager = employeeRepository.findById(departmentDto.getManagerId())
                    .orElseThrow(() -> new ResourceNotFoundException("Manager employee not found with id: " + departmentDto.getManagerId()));
            department.setManager(manager);

            if (manager.getUser() != null) {
                Role managerRole = roleRepository.findByName("ROLE_MANAGER")
                        .orElseThrow(() -> new ResourceNotFoundException("Role not found: ROLE_MANAGER"));
                manager.getUser().getRoles().add(managerRole);
                userRepository.save(manager.getUser());
            }
        } else {
            department.setManager(null);
        }

        Department updatedDepartment = departmentRepository.save(department);
        return mapToDto(updatedDepartment);
    }

    @Override
    public void deleteDepartment(Long departmentId) {
        Department department = departmentRepository.findById(departmentId)
                .orElseThrow(() -> new ResourceNotFoundException("Department is not exists with given id: " + departmentId));

        departmentRepository.delete(department);
    }

    // Mapper Methods
    private DepartmentDto mapToDto(Department department){
        String managerName = null;
        if (department.getManager() != null) {
            managerName = department.getManager().getFirstName() + " " + (department.getManager().getLastName() != null ? department.getManager().getLastName() : "");
            managerName = managerName.trim();
        }
        return new DepartmentDto(
                department.getId(),
                department.getName(),
                department.getDescription(),
                department.getManager() != null ? department.getManager().getId() : null,
                managerName
        );
    }

    private Department mapToEntity(DepartmentDto departmentDto){
        Department department = new Department();
        department.setName(departmentDto.getName());
        department.setDescription(departmentDto.getDescription());
        return department;
    }
}
