package com.ak.ems.service.impl;

import com.ak.ems.dto.EmployeeDto;
import com.ak.ems.entity.Employee;
import com.ak.ems.exception.ResourceNotFoundException;
import com.ak.ems.mapper.EmployeeMapper;
import com.ak.ems.repository.DepartmentRepository;
import com.ak.ems.repository.EmployeeRepository;
import com.ak.ems.repository.TeamRepository;
import com.ak.ems.repository.RoleRepository;
import com.ak.ems.repository.UserRepository;
import com.ak.ems.service.EmployeeService;
import com.ak.ems.entity.User;
import com.ak.ems.entity.Role;
import com.ak.ems.entity.Department;
import com.ak.ems.entity.Team;
import lombok.AllArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.HashSet;
import java.util.Set;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import com.ak.ems.response.PageResponse;

import java.util.List;
import java.util.stream.Collectors;


@AllArgsConstructor
@Service
@Transactional
public class EmployeeServiceImpl implements EmployeeService {

    private EmployeeRepository employeeRepository;
    private DepartmentRepository departmentRepository;
    private TeamRepository teamRepository;
    private UserRepository userRepository;
    private RoleRepository roleRepository;
    private com.ak.ems.repository.AttendanceRepository attendanceRepository;
    private com.ak.ems.repository.LeaveRequestRepository leaveRequestRepository;
    private com.ak.ems.repository.SkillRepository skillRepository;
    private com.ak.ems.repository.SalaryRecordRepository salaryRecordRepository;
    private com.ak.ems.repository.SalaryHistoryRepository salaryHistoryRepository;
    private com.ak.ems.repository.DocumentRepository documentRepository;
    private com.ak.ems.repository.AnnouncementRepository announcementRepository;
    private PasswordEncoder passwordEncoder;

    @Override
    public EmployeeDto createEmployee(EmployeeDto employeeDto) {

        if (employeeRepository.existsByEmail(employeeDto.getEmail())) {
            throw new IllegalArgumentException("Employee Email already exists: " + employeeDto.getEmail());
        }

        if (employeeDto.getUserId() != null && employeeRepository.existsByUser_Id(employeeDto.getUserId())) {
            throw new IllegalArgumentException("User with ID " + employeeDto.getUserId() + " is already assigned to another employee.");
        }

        Employee employee = EmployeeMapper.maptoEmployee(employeeDto);
        employee.setId(null); // Ensure ID is auto-generated by database during creation

        if (employee.getJoiningDate() == null) {
            employee.setJoiningDate(java.time.LocalDate.now());
        }

        // Handle inline user creation if username and password are provided
        if (employeeDto.getUsername() != null && !employeeDto.getUsername().isEmpty() &&
            employeeDto.getPassword() != null && !employeeDto.getPassword().isEmpty()) {
            
            if (userRepository.existsByUsername(employeeDto.getUsername())) {
                throw new IllegalArgumentException("Username already exists: " + employeeDto.getUsername());
            }
            if (userRepository.existsByEmail(employeeDto.getEmail())) {
                throw new IllegalArgumentException("User with this email already exists: " + employeeDto.getEmail());
            }

            User user = new User();
            user.setName(employeeDto.getFirstName() + " " + employeeDto.getLastName());
            user.setUsername(employeeDto.getUsername());
            user.setEmail(employeeDto.getEmail());
            user.setPassword(passwordEncoder.encode(employeeDto.getPassword()));

            String roleName = employeeDto.getRole() != null ? employeeDto.getRole() : "ROLE_EMPLOYEE";
            Role empRole = roleRepository.findByName(roleName).orElseGet(() -> {
                Role role = new Role();
                role.setName(roleName);
                return roleRepository.save(role);
            });

            Set<Role> roles = new HashSet<>();
            roles.add(empRole);
            user.setRoles(roles);

            User savedUser = userRepository.save(user);
            employee.setUser(savedUser);
        } else if (employeeDto.getUserId() != null) {
            employee.setUser(userRepository.findById(employeeDto.getUserId())
                    .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + employeeDto.getUserId())));
        }

        // Reset org details - logic will set them back
        employee.setDepartment(null);
        employee.setTeam(null);

        if (!"ROLE_ADMIN".equals(employeeDto.getRole())) {
            if (employeeDto.getTeamId() != null) {
                Team team = teamRepository.findById(employeeDto.getTeamId())
                        .orElseThrow(() -> new ResourceNotFoundException("Team not found with id: " + employeeDto.getTeamId()));
                employee.setTeam(team);
                // Inherit department from team if not explicitly provided
                if (employeeDto.getDepartmentId() == null) {
                    employee.setDepartment(team.getDepartment());
                }
            }

            if (employeeDto.getDepartmentId() != null) {
                Department department = departmentRepository.findById(employeeDto.getDepartmentId())
                        .orElseThrow(() -> new ResourceNotFoundException("Department not found with id: " + employeeDto.getDepartmentId()));
                employee.setDepartment(department);
            }
        }

        // Assign initial skills if provided
        if (employeeDto.getSkills() != null) {
            for (String skillName : employeeDto.getSkills()) {
                com.ak.ems.entity.Skill skill = skillRepository.findByNameIgnoreCase(skillName)
                        .orElseGet(() -> {
                            com.ak.ems.entity.Skill newSkill = new com.ak.ems.entity.Skill();
                            newSkill.setName(skillName);
                            return skillRepository.save(newSkill);
                        });
                employee.getSkills().add(skill);
            }
        }

        Employee savedEmployee = employeeRepository.save(employee);

        // Link back to Department or Team for leadership roles
        if ("ROLE_MANAGER".equals(employeeDto.getRole()) && employee.getDepartment() != null) {
            Department dept = employee.getDepartment();
            dept.setManager(savedEmployee);
            departmentRepository.save(dept);
        } else if ("ROLE_TEAM_LEADER".equals(employeeDto.getRole()) && employee.getTeam() != null) {
            Team team = employee.getTeam();
            team.setTeamLeader(savedEmployee);
            teamRepository.save(team);
        }

        return EmployeeMapper.maptoEmployeeDto(savedEmployee);
    }

    @Override
    public EmployeeDto getEmployeeById(Long employeeId) {
        Employee employee = employeeRepository.findById(employeeId).orElseThrow(() -> new ResourceNotFoundException("Employee is not exist with given id : " + employeeId));
        return EmployeeMapper.maptoEmployeeDto(employee);
    }

    @Override
    public PageResponse<EmployeeDto> getAllEmployees(String query, Long departmentId, Long teamId, int page, int size, String sortBy, String sortDir) {
        Sort sort = sortDir.equalsIgnoreCase(Sort.Direction.ASC.name()) ? Sort.by(sortBy).ascending()
                : Sort.by(sortBy).descending();

        Pageable pageable = PageRequest.of(page, size, sort);
        
        // If query is empty string, convert to null for JPQL IS NULL check
        if (query != null && query.trim().isEmpty()) {
            query = null;
        }

        Page<Employee> employeesPage = employeeRepository.searchEmployeesWithFilters(query, departmentId, teamId, pageable);

        List<Employee> employees = employeesPage.getContent();
        List<EmployeeDto> content = employees.stream().map(EmployeeMapper::maptoEmployeeDto).collect(Collectors.toList());

        return PageResponse.<EmployeeDto>builder()
                .content(content)
                .pageNo(employeesPage.getNumber())
                .pageSize(employeesPage.getSize())
                .totalElements(employeesPage.getTotalElements())
                .totalPages(employeesPage.getTotalPages())
                .last(employeesPage.isLast())
                .build();
    }

    @Override
    public EmployeeDto updateEmployee(Long employeeId, EmployeeDto updatedEmployeeDto) {

        Employee employee = employeeRepository.findById(employeeId).orElseThrow(() -> new RuntimeException("Employee is not exist with given id :" + employeeId));

        // Check if email is being changed and if new email already exists
        if (!employee.getEmail().equals(updatedEmployeeDto.getEmail()) && 
            employeeRepository.existsByEmail(updatedEmployeeDto.getEmail())) {
            throw new IllegalArgumentException("Employee Email already exists: " + updatedEmployeeDto.getEmail());
        }

        // Check if user is being changed and if new user is already assigned
        if (updatedEmployeeDto.getUserId() != null && 
            (employee.getUser() == null || !employee.getUser().getId().equals(updatedEmployeeDto.getUserId())) &&
            employeeRepository.existsByUser_Id(updatedEmployeeDto.getUserId())) {
            throw new IllegalArgumentException("User with ID " + updatedEmployeeDto.getUserId() + " is already assigned to another employee.");
        }

        employee.setFirstName(updatedEmployeeDto.getFirstName());
        employee.setLastName(updatedEmployeeDto.getLastName());
        employee.setEmail(updatedEmployeeDto.getEmail());
        employee.setPhone(updatedEmployeeDto.getPhone());
        employee.setDesignation(updatedEmployeeDto.getDesignation());
        employee.setJoiningDate(updatedEmployeeDto.getJoiningDate());
        employee.setAddress(updatedEmployeeDto.getAddress());

        // Sync with User account if exists
        if (employee.getUser() != null) {
            User user = employee.getUser();
            user.setName(updatedEmployeeDto.getFirstName() + " " + updatedEmployeeDto.getLastName());
            user.setEmail(updatedEmployeeDto.getEmail());
            
            // Allow updating username if provided
            if (updatedEmployeeDto.getUsername() != null && !updatedEmployeeDto.getUsername().isEmpty()) {
                if (!user.getUsername().equals(updatedEmployeeDto.getUsername()) && 
                    userRepository.existsByUsername(updatedEmployeeDto.getUsername())) {
                    throw new IllegalArgumentException("Username already exists: " + updatedEmployeeDto.getUsername());
                }
                user.setUsername(updatedEmployeeDto.getUsername());
            }
            
            // Allow updating password if provided
            if (updatedEmployeeDto.getPassword() != null && !updatedEmployeeDto.getPassword().isEmpty()) {
                user.setPassword(passwordEncoder.encode(updatedEmployeeDto.getPassword()));
            }
            
            userRepository.save(user);
        }

        // Reset org details before re-assigning based on DTO
        employee.setDepartment(null);
        employee.setTeam(null);

        if (!"ROLE_ADMIN".equals(updatedEmployeeDto.getRole())) {
            if (updatedEmployeeDto.getTeamId() != null) {
                Team team = teamRepository.findById(updatedEmployeeDto.getTeamId())
                        .orElseThrow(() -> new ResourceNotFoundException("Team not found with id: " + updatedEmployeeDto.getTeamId()));
                employee.setTeam(team);
                if (updatedEmployeeDto.getDepartmentId() == null) {
                    employee.setDepartment(team.getDepartment());
                }
            }

            if (updatedEmployeeDto.getDepartmentId() != null) {
                Department department = departmentRepository.findById(updatedEmployeeDto.getDepartmentId())
                        .orElseThrow(() -> new ResourceNotFoundException("Department not found with id: " + updatedEmployeeDto.getDepartmentId()));
                employee.setDepartment(department);
            }
        }

        if (updatedEmployeeDto.getUserId() != null) {
            employee.setUser(userRepository.findById(updatedEmployeeDto.getUserId())
                    .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + updatedEmployeeDto.getUserId())));
        } else {
            employee.setUser(null);
        }

        // Sync Skills
        if (updatedEmployeeDto.getSkills() != null) {
            employee.getSkills().clear();
            for (String skillName : updatedEmployeeDto.getSkills()) {
                com.ak.ems.entity.Skill skill = skillRepository.findByNameIgnoreCase(skillName)
                        .orElseGet(() -> {
                            com.ak.ems.entity.Skill newSkill = new com.ak.ems.entity.Skill();
                            newSkill.setName(skillName);
                            return skillRepository.save(newSkill);
                        });
                employee.getSkills().add(skill);
            }
        }

        Employee updatedEmployee = employeeRepository.save(employee);

        return EmployeeMapper.maptoEmployeeDto(updatedEmployee);

    }

    @Override
    public void deleteEmployee(Long employeeId) {
        Employee employee = employeeRepository.findById(employeeId)
                .orElseThrow(() -> new ResourceNotFoundException("Employee not found with id: " + employeeId));
        
        // 1. Clear references as Manager in Departments
        departmentRepository.findAll().stream()
                .filter(d -> d.getManager() != null && d.getManager().getId().equals(employeeId))
                .forEach(d -> {
                    d.setManager(null);
                    departmentRepository.save(d);
                });

        // 2. Clear references as Team Leader in Teams
        teamRepository.findAll().stream()
                .filter(t -> t.getTeamLeader() != null && t.getTeamLeader().getId().equals(employeeId))
                .forEach(t -> {
                    t.setTeamLeader(null);
                    teamRepository.save(t);
                });

        // 3. Delete Attendance records
        attendanceRepository.findByEmployeeId(employeeId).forEach(a -> attendanceRepository.delete(a));

        // 4. Delete Leave records
        leaveRequestRepository.findByEmployeeId(employeeId).forEach(l -> leaveRequestRepository.delete(l));

        // 5. Delete Salary records
        salaryRecordRepository.findByEmployeeIdOrderByYearDescMonthDesc(employeeId).forEach(sr -> salaryRecordRepository.delete(sr));

        // 6. Delete Salary History records
        salaryHistoryRepository.findByEmployeeIdOrderByChangedAtDesc(employeeId).forEach(sh -> salaryHistoryRepository.delete(sh));

        // 7. Delete Document records
        documentRepository.findByEmployeeId(employeeId).forEach(doc -> documentRepository.delete(doc));

        // 8. Delete Announcements created by this employee's user
        if (employee.getUser() != null) {
            announcementRepository.findAll().stream()
                    .filter(a -> a.getCreatedBy() != null && a.getCreatedBy().getId().equals(employee.getUser().getId()))
                    .forEach(a -> announcementRepository.delete(a));
        }

        // 9. Delete the Employee
        employeeRepository.delete(employee);
        
        // 10. Delete the User account
        if (employee.getUser() != null) {
            userRepository.delete(employee.getUser());
        }
    }

    @Override
    public EmployeeDto getEmployeeByUsername(String username) {
        Employee employee = employeeRepository.findByUser_Username(username)
                .orElseThrow(() -> new ResourceNotFoundException("Employee not found for username: " + username));
        return EmployeeMapper.maptoEmployeeDto(employee);
    }

    @Override
    public List<EmployeeDto> getEmployeesByDesignation(String designation) {
        return employeeRepository.findByDesignation(designation).stream()
                .map(EmployeeMapper::maptoEmployeeDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<EmployeeDto> getEmployeesBySkill(String skillName) {
        return employeeRepository.findBySkills_Name(skillName).stream()
                .map(EmployeeMapper::maptoEmployeeDto)
                .collect(Collectors.toList());
    }

    @Override
    public void addSkillToEmployee(Long employeeId, String skillName) {
        Employee employee = employeeRepository.findById(employeeId)
                .orElseThrow(() -> new ResourceNotFoundException("Employee not found"));
        
        com.ak.ems.entity.Skill skill = skillRepository.findByNameIgnoreCase(skillName)
                .orElseGet(() -> {
                    com.ak.ems.entity.Skill newSkill = new com.ak.ems.entity.Skill();
                    newSkill.setName(skillName);
                    return skillRepository.save(newSkill);
                });
        
        employee.getSkills().add(skill);
        employeeRepository.save(employee);
    }


}
